[pytest]
# Indique à pytest de chercher les tests uniquement dans le dossier 'test_unitaire'
testpaths = test_unitaire
# Ajoute des options par défaut, comme le mode verbeux (-v)
addopts = -v
# Ajoute le répertoire courant au PYTHONPATH pour trouver les modules (services, repositories, etc.)
pythonpath = .